image:
  file: .gitpod.Dockerfile

tasks:
  - command: |
      # Start MEGA CMD server
      mega-cmd-server &
      sleep 5  # Wait for server to start
      
      # You can add any additional startup commands here
      
      # Switch to Zsh as the default shell
      exec zsh

ports:
  - port: 6080
    onOpen: open-preview