image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      chmod +x install-mega.sh
      chmod +x mount-cloud-storage.sh
    command: |
      ./install-mega.sh
      # Start MEGA CMD server
      megacmd-server &
      # Mount MEGA storage
      ./mount-cloud-storage.sh

ports:
  - port: 6080
    onOpen: open-preview
