image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Make scripts executable
      chmod +x install-mega.sh
      chmod +x mount-cloud-storage.sh
      chmod +x zsh_setup.sh  # Ensure Zsh setup script is executable

      # Run Zsh setup script
      ./zsh_setup.sh
    
      # Run MEGA installation script
      ./install-mega.sh
      
      # Start MEGA CMD server
      mega-cmd-server &
      sleep 10  # Wait for server to start

      # Mount MEGA storage
      ./mount-cloud-storage.sh
      sleep 10  # Wait for mounting to complete
      
  - command: |
      # Switch to Zsh as the default shell
      zsh

ports:
  - port: 6080
    onOpen: open-preview
