version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: myproject/base_image:latest

  mega:
    build:
      context: .
      dockerfile: Dockerfile.mega
    image: myproject/mega_image:latest
    depends_on:
      - base

  zsh:
    build:
      context: .
      dockerfile: Dockerfile.zsh
    image: myproject/zsh_image:latest
    depends_on:
      - base

  final:
    build:
      context: .
      dockerfile: Dockerfile.final
    image: myproject/final_image:latest
    depends_on:
      - base
      - mega
      - zsh