FROM local/base_image:latest

# Copy scripts
COPY *.sh /codespace/
RUN find /codespace -name "*.sh" -exec chmod +x {} \;

EXPOSE 5901 5902 5903 8080

# CMD ["/bin/zsh"]
CMD ["tail", "-f", "/dev/null"]