services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: local/base_image:latest

  mega:
    build:
      context: .
      dockerfile: Dockerfile.mega
    image: local/mega_image:latest
    depends_on:
      - base

  zsh:
    build:
      context: .
      dockerfile: Dockerfile.zsh
    image: local/zsh_image:latest
    depends_on:
      - base

  final:
    build:
      context: .
      dockerfile: Dockerfile.final
    image: local/final_image:latest
    depends_on:
      - base
      - mega
      - zsh
    volumes:
      - ..:/workspace:cached
    environment:
      - MEGA_EMAIL
      - MEGA_PASSWORD
      - VNC_PASSWORD=1234
    ports:
      - "5901:5901"
      - "5902:5902"
      - "5903:5903"
      - "8080:8080"