version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: base_image

  mega:
    build:
      context: .
      dockerfile: Dockerfile.mega
    depends_on:
      - base
    image: mega_image

  zsh:
    build:
      context: .
      dockerfile: Dockerfile.zsh
    depends_on:
      - base
    image: zsh_image

  final:
    build:
      context: .
      dockerfile: Dockerfile.final
    depends_on:
      - base
      - mega
      - zsh
    image: final_image
