version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: base_image

  mega:
    build:
      context: .
      dockerfile: Dockerfile.mega
    image: mega_image

  zsh:
    build:
      context: .
      dockerfile: Dockerfile.zsh
    image: zsh_image

  final:
    build:
      context: .
      dockerfile: Dockerfile.final
    image: final_image